### ISSUE TITLE
mint.js "Fail with error 'Ownable: caller is not the owner'"

### ISSUE THREAD

**Issue by SavvyEngineer** [ProjectOpenSea/opensea-creatures#47] opened 2020-12-16 09:34 UTC
Hi first of all thanks for your tutorial really helpfull i used your repo and created a simple nft conract and a nft factory conract
and i deployed them into rinkeby testnet and verified them but when i try to use the mint.js script the script crashed with error:
```
(node:15292) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
```

and in the etherscan:
```
Fail with error 'Ownable: caller is not the owner'
```

i checked my wallet address for million times and even i lowerd cased them and i have no clue to solve this please help.thanks

**Comment by alexanderatallah** [comment] 2020-12-16 15:31
Are you using the same wallet seed phrase for the MNEMONIC env variable that you used to deploy the contract?

**Comment by SavvyEngineer** [comment] 2020-12-16 16:00
yup they are the same.

**Comment by DJViau** [comment] 2020-12-16 17:59
Closing because this issue appears to have been caused by an inadvertent contract ownership transfer.

**Closed by DJViau** 2020-12-16 17:59 UTC

**Comment by ahmedelgammal** [comment] 2021-03-08 18:49
Not sure why this issue is closed without an answer. I am getting the same problem. I see also issue 50 is the same. so this keeps coming to different users. so we appreciate an answer.

**Comment by alexanderatallah** [comment] 2021-03-08 19:01
@ahmedelgammal if you run `./flatten.sh`, can you verify that your contract is inheriting from Ownable? should show up in the inheritance tree

**Comment by ahmedelgammal** [comment] 2021-03-08 20:51
The are inheriting from Ownable .

**Comment by Skillvendor** [comment] 2021-08-08 09:55
Still an issue, why closed?

**Comment by ranjancse26** [comment] 2021-08-23 15:32
> Closing because this issue appears to have been caused by an inadvertent contract ownership transfer.

I am facing the same issues. Please reopen the issue.

**Comment by SavvyEngineer** [comment] 2021-08-23 15:56
It was for a long time ago but i think the problem was that i had deployed an Erc-1155 with factory method and in that situation using erc-721 mint.js is not possible

**Comment by fdchiu** [comment] 2021-09-24 22:55
I encountered the same error and there is a good explanation for this:
The ownership of Creature contract IS transferred to CreatureFactory contract as indicated in 2_deploy_contract.js. Your creator wallet is no longer the owner! 

This is not explained at all in OpenSea's original documentation of code comments. See more detailed explanation on stack-exchange here: [https://ethereum.stackexchange.com/questions/107158/opensea-creatures-contract-mint-function-not-working/110526#110526](url)

**Comment by yarg119** [comment] 2022-06-10 21:05
One reason this error can pop up is if you have an embedded mint function within your targeted mint function that has "onlyOwner" next to it "nonReentrant" can also have the same effect.
