### ISSUE TITLE
Deployment of the contract

### ISSUE THREAD

**Issue by Lynaj** [ProjectOpenSea/opensea-creatures#4] opened 2019-01-09 06:56 UTC
Migrations are being created in a quite smooth way, but whenever it comes to the process of deploying it on the network - it simply hangs & stops working

Solution:
`npm install --save truffle-hdwallet-provider@web3-one`

**Comment by pkrasam** [comment] 2019-03-06 06:54
71 verbose stack Error: Command failed: /usr/local/bin/git submodule update -q --init --recursive
71 verbose stack error: could not lock config file .git/config: Permission denied
71 verbose stack error: could not lock config file .git/config: Permission denied
71 verbose stack fatal: Failed to register url for submodule path 'src/wyvern-ethereum'
71 verbose stack
71 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
71 verbose stack     at ChildProcess.emit (events.js:189:13)
71 verbose stack     at maybeClose (internal/child_process.js:970:16)
71 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
72 verbose cwd /Users/pk/Documents/code/opensea-creatures
73 verbose Darwin 18.2.0
74 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "truffle-hdwallet-provider@web3-one"
75 verbose node v10.15.1
76 verbose npm  v6.4.1
77 error code 128
78 error Command failed: /usr/local/bin/git submodule update -q --init --recursive
78 error error: could not lock config file .git/config: Permission denied
78 error error: could not lock config file .git/config: Permission denied
78 error fatal: Failed to register url for submodule path 'src/wyvern-ethereum'
79 verbose exit [ 1, true ]

**Comment by Lynaj** [comment] 2019-03-06 08:42
> 71 verbose stack Error: Command failed: /usr/local/bin/git submodule update -q --init --recursive
> 71 verbose stack error: could not lock config file .git/config: Permission denied
> 71 verbose stack error: could not lock config file .git/config: Permission denied
> 71 verbose stack fatal: Failed to register url for submodule path 'src/wyvern-ethereum'
> 71 verbose stack
> 71 verbose stack at ChildProcess.exithandler (child_process.js:294:12)
> 71 verbose stack at ChildProcess.emit (events.js:189:13)
> 71 verbose stack at maybeClose (internal/child_process.js:970:16)
> 71 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 72 verbose cwd /Users/pk/Documents/code/opensea-creatures
> 73 verbose Darwin 18.2.0
> 74 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "truffle-hdwallet-provider@web3-one"
> 75 verbose node v10.15.1
> 76 verbose npm v6.4.1
> 77 error code 128
> 78 error Command failed: /usr/local/bin/git submodule update -q --init --recursive
> 78 error error: could not lock config file .git/config: Permission denied
> 78 error error: could not lock config file .git/config: Permission denied
> 78 error fatal: Failed to register url for submodule path 'src/wyvern-ethereum'
> 79 verbose exit [ 1, true ]

try with sudo:

**Comment by alexanderatallah** [comment] 2019-04-18 19:42
This should be fixed now! let us know if not

**Comment by yjkimjunior** [comment] 2020-06-27 15:20
@alexanderatallah it is not :(

**Comment by yjkimjunior** [comment] 2020-07-08 11:34
Hey there, any updates on this?

**Comment by alexanderatallah** [comment] 2020-07-08 15:57
@robmyers any ideas here what might be going on?

**Comment by robmyers** [comment] 2020-07-08 16:25
I'll take a look.

**Comment by robmyers** [comment] 2020-07-09 02:20
I can't reproduce this with a Rinkeby deploy using node 11 and a fresh npm install.

@yjkimjunior can you paste the output of the error here?

**Comment by yjkimjunior** [comment] 2020-07-09 05:21
compiles with some warnings and then it just hangs here. I made a PR to fix teh compilation warnings, but even on that branch it'll compile without warnings then just hang with no more output.

```
$ DEPLOY_CREATURES_SALE=1 yarn truffle deploy --network rinkeby
yarn run v1.22.4
$ /Users/yj/Developer/opensea-creatures/node_modules/.bin/truffle deploy --network rinkeby

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
> Compiling ./contracts/Creature.sol
> Compiling ./contracts/CreatureAccessory.sol
> Compiling ./contracts/CreatureFactory.sol
> Compiling ./contracts/CreatureLootBox.sol
> Compiling ./contracts/ERC721Tradable.sol
✔ Fetching solc version list from solc-bin. Attempt #1
> Compilation warnings encountered:

    /Users/yj/Developer/opensea-creatures/contracts/CreatureFactory.sol:119:25: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  function transferFrom(address _from, address _to, uint256 _tokenId) public {
                        ^-----------^
,/Users/yj/Developer/opensea-creatures/contracts/CreatureFactory.sol:151:20: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  function ownerOf(uint256 _tokenId) public view returns (address _owner) {
                   ^--------------^
,/Users/yj/Developer/opensea-creatures/contracts/ERC721Tradable.sol:52:3: Warning: Function state mutability can be restricted to pure
  function baseTokenURI() public view returns (string memory) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/yj/Developer/opensea-creatures/contracts/Creature.sol:17:3: Warning: Function state mutability can be restricted to pure
  function contractURI() public view returns (string memory) {
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/yj/Developer/opensea-creatures/contracts/CreatureAccessory.sol:18:3: Warning: Function state mutability can be restricted to pure
  function contractURI() public view returns (string memory) {
  ^ (Relevant source part starts here and spans across multiple lines).

^[[B> Artifacts written to /Users/yj/Developer/opensea-creatures/build/contracts
> Compiled successfully using:
   - solc: 0.5.17+commit.d19bba13.Emscripten.clang

```

**Comment by yjkimjunior** [comment] 2020-07-09 05:23
i've tried with node 11 and 12, same result

**Comment by yjkimjunior** [comment] 2020-07-09 05:24
after first time compiling it just hangs here:

```
$ DEPLOY_CREATURES_SALE=1 yarn truffle deploy --network rinkeby
yarn run v1.22.4
$ /Users/yj/Developer/opensea-creatures/node_modules/.bin/truffle deploy --network rinkeby

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

```

**Comment by robmyers** [comment] 2020-07-10 00:16
@yjkimjunior thank you!

I can reproduce that with either:
* Node 8.11 and yarn truffle.
* Node 8.11 and npx truffle.
* Node 8.11 and truffle.
* Node 11 and yarn truffle.
* Node 11 and npx truffle.

To use yarn I have to delete the "engines" entry of package.json, otherwise it fails to install with clashing node versions in requirements.

So the simple fix is to use node 11+, npm, and truffle installed globally with npm install -g truffle. But I'm concerned that this will just mask the actual problem.

I'm confused as to why we are seeing these problems. I will clean up my node install and see what I can do with a fresh

**Comment by yjkimjunior** [comment] 2020-07-10 04:44
ah okay then. I used yarn because the docs say to run with `DEPLOY_CREATURES_SALE=1 yarn truffle deploy --network rinkeby`. Maybe just a matter of updating the docs?

> So the simple fix is to use node 11+, npm, and truffle installed globally with npm install -g truffle. But I'm concerned that this will just mask the actual problem.

doing this successfully compiles and the process exits, but doesn't output any contract address at the end. It literally is the same as above except that it exits...

```
YJs-MacBook-Pro:opensea-creatures yj$ DEPLOY_CREATURES_SALE=1 truffle deploy --network rinkeby

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

YJs-MacBook-Pro:opensea-creatures yj$
```

**Comment by robmyers** [comment] 2020-07-10 04:56
If you have already deployed the contracts that's the expected behavior.

If you wish to redeploy the contracts append `--reset` to the command. That will overwrite the addresses of the previously deployed versions of the same contarcts on that chain, though, so be careful with it.

**Comment by robmyers** [comment] 2020-07-14 04:18
Something didn't feel right about this so I dug in further.

Truffle 5.1.32 works however you call it. I had that installed with truffle -g, so it worked.

Truffle 5.1.34 does *not* work, and that is the version that package.json's spec of "truffle": "^5.1.30" installs.

So a fix would be to change the spec to "truffle": "5.1.32" until this is no longer an issue.

I'll see if there are any bugs against truffle for this.

**Comment by alexanderatallah** [comment] 2020-10-18 22:19
Closing this for now (moved to yarn)

**Closed by alexanderatallah** 2020-10-18 22:19 UTC
